Sure, here's the contents for the file: /shaw-webmail/shaw-webmail/netlify.toml

[build]
  publish = "public"
  command = "npm run build"

[dev]
  command = "npm run start"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200